---

- hosts: cluster
  remote_user: root
  tasks:

  - name: install haproxy and keepalived
    apt_rpm:
      name:
        - haproxy
        - keepalived
      state: present
      update_cache: yes

  - name: create haproxy group
    group:
      name: "haproxy"
      state: present

  - name: create haproxy user
    user:
      name: "haproxy"
      state: present
      password: "!"
      shell: /bin/bash
      group: "haproxy"

  - name: set ip_nonlocal_bind
    sysctl:
      name: net.ipv4.ip_nonlocal_bind
      value: '1'
      state: present
      reload: yes

  - name: haproxy config
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: keepalived config
    template:
      src: ./keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf

  - name: enable and restart keepalived
    service:
      name: 'keepalived'
      state: restarted
      enabled: yes

  - name: enable and restart haproxy
    service:
      name: 'haproxy'
      state: restarted
      enabled: yes
